Repository hupkit/hupkit, pull requests merged in 2020-12, with the labels that each got.

#91 Fix MergeHandler commit with no author info
  src/Cli/Handler/MergeHandler.php
  src/Service/GitHub.php
  tests/Handler/MergeHandlerTest.php
Labels: Bug

#93 Add php8 support
  .github/workflows/ci.yaml
  README.md
  composer.json
  composer.lock
  src/Container.php
  src/Service/GitHub.php
Labels: BC Break, Feature

#94 Remove automatically closing of linked issues
  src/Cli/Handler/MergeHandler.php
  src/Service/CliProcess.php
  src/Service/GitHub.php
  tests/Handler/MergeHandlerTest.php
Labels: BC Break

#95 [Merge] Automatically clean-up the feature branch
  docs/commands/merge.md
  src/Cli/Handler/MergeHandler.php
  src/Cli/HubKitApplicationConfig.php
  tests/Handler/MergeHandlerTest.php
Labels: BC Break, Enhancement
